#!/usr/bin/env bash
# 轻量 VPS 网络调优。只在向导启用时写入独立 sysctl.d 文件。

apply_perf_tuning() {
  [ "${KERNEL_LOW_LATENCY:-0}" = "1" ] || return 0
  [ -d /proc/sys/net/ipv4 ] || { warn "当前内核不支持 sysctl 网络调优，跳过"; return 0; }

  local conf=/etc/sysctl.d/99-reality-deployer.conf
  local cc=bbr
  local features=()
  if ! grep -qw bbr /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
    warn "内核未提供 BBR，保留当前拥塞控制，仅启用 fq/TFO（如可用）"
    cc=""
  fi

  {
    echo "# Generated by reality-deployer."
    if [ -e /proc/sys/net/core/default_qdisc ]; then
      echo "net.core.default_qdisc=fq"
      features+=("fq")
    fi
    if [ -n "$cc" ] && [ -e /proc/sys/net/ipv4/tcp_congestion_control ]; then
      echo "net.ipv4.tcp_congestion_control=$cc"
      features+=("$cc")
    fi
    if [ -e /proc/sys/net/ipv4/tcp_fastopen ]; then
      echo "net.ipv4.tcp_fastopen=3"
      features+=("tcp_fastopen")
    fi
  } >"$conf"

  sysctl --system >/dev/null 2>&1 || warn "sysctl 应用失败，请手动检查 $conf"
  if [ "${#features[@]}" -eq 0 ]; then
    warn "未发现可应用的低延迟 sysctl 键，已保留空配置 $conf"
    return 0
  fi
  ok "低延迟内核参数已应用（${features[*]}）"
}
