package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"reality-deployer/internal/combo"
	"reality-deployer/internal/manifest"
)

// staging 子目录（固定布局；install.sh 按此映射拷贝到系统路径）。
const (
	stageXray    = "xray"
	stageAngie   = "angie"
	stageDecoy   = "decoy"
	stageSystemd = "systemd"
)

// Render 把 manifest 渲染到 baseDir 下：staging/（配置 + ufw_rules.sh）与 apply.env。
func Render(m *manifest.Manifest, baseDir string) error {
	staging := filepath.Join(baseDir, "staging")
	for _, d := range []string{stageXray, stageAngie, stageDecoy, stageSystemd} {
		if err := os.MkdirAll(filepath.Join(staging, d), 0o755); err != nil {
			return err
		}
	}

	xjson, err := Xray(m)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(staging, stageXray, "config.json"), xjson, 0o644); err != nil {
		return err
	}

	angieConf, err := Angie(m)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(staging, stageAngie, m.Domain+".conf"), []byte(angieConf), 0o644); err != nil {
		return err
	}

	decoy, err := Decoy(m.Domain)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(staging, stageDecoy, "index.html"), []byte(decoy), 0o644); err != nil {
		return err
	}

	unit, err := Systemd()
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(staging, stageSystemd, "xray.service"), []byte(unit), 0o644); err != nil {
		return err
	}

	ufw := UFWScript(m.Firewall)
	if err := writeFile(filepath.Join(staging, "ufw_rules.sh"), []byte(ufw), 0o644); err != nil {
		return err
	}

	env := ApplyEnv(m, staging)
	if err := writeFile(filepath.Join(baseDir, "apply.env"), []byte(env), 0o600); err != nil {
		return err
	}
	return nil
}

func writeFile(path string, data []byte, mode os.FileMode) error {
	return os.WriteFile(path, data, mode)
}

// ApplyEnv 生成 bash 可 source 的标量环境文件。
func ApplyEnv(m *manifest.Manifest, stagingDir string) string {
	var b strings.Builder
	b.WriteString("# Generated by reality-deployer. Sourced by install.sh.\n")
	fmt.Fprintf(&b, "DOMAIN=%q\n", m.Domain)
	fmt.Fprintf(&b, "EMAIL=%q\n", m.Email)
	fmt.Fprintf(&b, "PUBLIC_IP=%q\n", m.PublicIP)
	fmt.Fprintf(&b, "SSH_PORT=%d\n", m.SSHPort)
	fmt.Fprintf(&b, "STAGING=%q\n", stagingDir)
	fmt.Fprintf(&b, "ROUTING_PRESET=%q\n", m.Routing.Preset)
	fmt.Fprintf(&b, "ROUTING_ADBLOCK=%d\n", btoi(m.Routing.AdBlock))
	fmt.Fprintf(&b, "KERNEL_LOW_LATENCY=%d\n", btoi(m.Tuning.KernelLowLatency))

	b.WriteString("\n# combos (0/1 flags)\n")
	var (
		enReality, enTLS, enXHTTP, enHy2   = 0, 0, 0, 0
		hy2Port                            int
		hy2Hop                             string
		realitySrc, realitySNI, realityPub string
	)
	if m.Reality != nil {
		realitySrc = string(m.Reality.Source)
		if len(m.Reality.ServerNames) > 0 {
			realitySNI = m.Reality.ServerNames[0]
		}
		realityPub = m.Reality.PublicKey
	}
	for _, c := range m.Combos {
		switch c.Type {
		case combo.TypeVLESSReality:
			enReality = 1
		case combo.TypeVLESSTLS:
			enTLS = 1
		case combo.TypeVLESSXHTTP:
			enXHTTP = 1
		case combo.TypeHysteria2:
			enHy2 = 1
			hy2Port = c.Port
			hy2Hop = c.Hy2PortHop
		}
	}
	fmt.Fprintf(&b, "ENABLE_VLESS_REALITY=%d\n", enReality)
	fmt.Fprintf(&b, "ENABLE_VLESS_TLS=%d\n", enTLS)
	fmt.Fprintf(&b, "ENABLE_VLESS_XHTTP=%d\n", enXHTTP)
	fmt.Fprintf(&b, "ENABLE_HYSTERIA2=%d\n", enHy2)
	if enHy2 == 1 {
		fmt.Fprintf(&b, "HY2_PORT=%d\n", hy2Port)
		fmt.Fprintf(&b, "HY2_PORTHOP=%q\n", hy2Hop)
	}
	if enReality == 1 {
		fmt.Fprintf(&b, "REALITY_SOURCE=%q\n", realitySrc)
		fmt.Fprintf(&b, "REALITY_SERVER_NAME=%q\n", realitySNI)
		fmt.Fprintf(&b, "REALITY_PUBLIC_KEY=%q\n", realityPub)
	}
	return b.String()
}

func btoi(b bool) int {
	if b {
		return 1
	}
	return 0
}
