package config

import (
	"fmt"
	"strings"

	"reality-deployer/internal/manifest"
)

// ufwSpec 把一条规则转成 ufw 端口说明，如 "22/tcp"、"20000:50000/udp"。
func ufwSpec(r manifest.UFWRule) string {
	if r.Range != "" {
		return r.Range + "/" + r.Proto
	}
	return fmt.Sprintf("%d/%s", r.Port, r.Proto)
}

// UFWScript 生成 ufw_rules.sh：提供 ufw_apply / ufw_revert 两个函数，
// 分别供 install.sh / uninstall.sh 调用，规则来自 manifest.Firewall。
func UFWScript(fw manifest.Firewall) string {
	var b strings.Builder
	b.WriteString("# Generated by reality-deployer. do not edit.\n")
	b.WriteString("# 提供 ufw_apply / ufw_revert；规则与 manifest.Firewall 一一对应。\n\n")

	b.WriteString("ufw_apply() {\n")
	b.WriteString("  ufw --force default deny incoming\n")
	b.WriteString("  ufw --force default allow outgoing\n")
	for _, r := range fw.Rules {
		fmt.Fprintf(&b, "  ufw --force allow %s   # %s\n", ufwSpec(r), r.Note)
	}
	b.WriteString("}\n\n")

	b.WriteString("ufw_revert() {\n")
	for _, r := range fw.Rules {
		fmt.Fprintf(&b, "  ufw --force delete allow %s   # %s\n", ufwSpec(r), r.Note)
	}
	b.WriteString("}\n")
	return b.String()
}
